### ISSUE TITLE
Random item keep

### ISSUE THREAD

**Issue by anhcraft** [anhcraft/AdvancedKeep#83]
With dropped items, if option random_keep enabled, some of them will be kept for free.
Default chance for all material is 0.5
Can specify chance for a material, e.g: diamond sword has 0.6 chance
E.g:
```
default_chance: 0.5
specify_chance:
  diamond_sword: 0.6
  bow: 0.4
```
